"""enforce one active subscription per customer

Revision ID: 8e03e4ac3cad
Revises: 80ef86214efb
Create Date: 2026-10-10 13:48:52.897061

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e03e4ac3cad'
down_revision: Union[str, Sequence[str], None] = '80ef86214efb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('uq_active_subscription_per_customer', 'subscriptions', ['customer_id'], unique=True, postgresql_where=sa.text("status = 'ACTIVE'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_active_subscription_per_customer', table_name='subscriptions', postgresql_where=sa.text("status = 'ACTIVE'"))
    # ### end Alembic commands ###
